const opdTable = [
  {
    id: 1,
    name: "Prof.(Dr.) Sudhir Kumar",
    department: "Orthopaedics",
    designation: "Managing Director, Senior Consultant & HOD(Orthoo)",
    opd_timing: "09:00 am To 05:00 pm",
    days: "Mon to Fri",
  },
  {
    id: 2,
    name: "Dr. Vandana Prasad",
    department: "Ophthalmology",
    designation: "Director, Senior Consultant & HOD(Ophthalmology)",
    opd_timing: "11:30 am to 05:00 pm",
    days: "Mon to Sat",
  },
  {
    id: 3,
    name: "Prof.(Dr.) Ajay Kumar Verma",
    department: "Orthopaedics",
    designation: "Senior Consultant",
    opd_timing: "09:00 am To 03:00 pm",
    days: "Mon to Fri",
  },
  {
    id: 4,
    name: "Dr. Nilay Kumar",
    department: "Orthopaedics",
    designation: "	Specialist & Consultant",
    opd_timing: "09:00 am To 05:00 pm",
    days: "Mon to Fri",
  },
  {
    id: 4,
    name: "Dr. Akshay Kumar Sinha",
    department: "Orthopaedics",
    designation: "Senior Consultant",
    opd_timing: "06:00 pm To 06:00 am",
    days: "Mon to Fri",
  },
  {
    id: 5,
    name: "Dr. Abhishek Pandey",
    department: "Orthopaedics",
    designation: "Senior Consultant",
    opd_timing: "09:00 am To 05:00 pm",
    days: "	Mon to sat",
  },
  {
    id: 6,
    name: "Dr. B.V.Hargave",
    department: "Orthopaedics",
    designation: "Senior Medical Officer",
    opd_timing: "09:00 am To 05:00 pm",
    days: "	Mon to Sat",
  },
  {
    id: 7,
    name: "Dr. B.K. Sinha",
    department: "Orthopaedics",
    designation: "Senior Consultant",
    opd_timing: "	08:30 am To 02:30 pm",
    days: "Mon to Fri & sun",
  },
  {
    id: 8,
    name: "Dr. Sindhu Kumari",
    department: "Ophthalmology",
    designation: "Senior Consultant",
    opd_timing: "09:00 am To 5:00 pm",
    days: "Mon to Sat",
  },
  {
    id: 9,
    name: "Dr. Kumar Abhishek",
    department: "	Ophthalmology",
    designation: "Senior Consultant",
    opd_timing: "On Call",
    days: "Mon to Sat",
  },
  {
    id: 10,
    name: "Dr. Neeraj Kumar",
    department: "	Ophthalmology",
    designation: "Senior Consultant",
    opd_timing: "10:00 am to 11:00 am",
    days: "	Wed",
  },
];

export default opdTable;

export const consultantTable = [
  {
    id: 1,
    name: "Dr. Ashok Kumar Singh",
    department: "Emergency & Trauma",
    timing: "08:00 am To 02:00 pm",
    days: "Mon to Sat",
  },
  {
    id: 2,
    name: "Dr. Manoj Thomas Kandulna",
    department: "Emergency & Trauma",
    timing: "",
    days: "Mon & Thur",
  },
  {
    id: 3,
    name: "Dr. Brajesh Kumar",
    department: "Emergency & Trauma",
    timing: "",
    days: "Tue & Fri",
  },
  {
    id: 4,
    name: "Dr. Sunil George Kandulna",
    department: "Emergency & Trauma",
    timing: "",
    days: "Wed to Sat",
  },
];
